<?xml version="1.0" encoding="utf-8"?><Database Name="CJLSFOODSPAYROLL" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NEIL\SQLEXPRESS;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=True" SettingsObjectName="CJLS_FOODS_PAYROLL_SYSTEM.Properties.Settings" SettingsPropertyName="CJLSFOODSPAYROLLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Deductions" Member="tbl_Deductions">
    <Type Name="tbl_Deduction">
      <Column Name="DeductionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeductionName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeductionFlatRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DeductionPercentRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="tbl_Deduction_tbl_DeductionsLog" Member="tbl_DeductionsLogs" ThisKey="DeductionID" OtherKey="DeductionID" Type="tbl_DeductionsLog" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Users" Member="tbl_Users">
    <Type Name="tbl_User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecretQuestion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecretAnswer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tbl_Employee_tbl_User" Member="tbl_Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="tbl_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_DeductionsLog" Member="tbl_DeductionsLogs">
    <Type Name="tbl_DeductionsLog">
      <Column Name="DeductionsLogID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeductionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateApplied" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_Deduction_tbl_DeductionsLog" Member="tbl_Deduction" ThisKey="DeductionID" OtherKey="DeductionID" Type="tbl_Deduction" IsForeignKey="true" />
      <Association Name="tbl_Employee_tbl_DeductionsLog" Member="tbl_Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="tbl_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Employees" Member="tbl_Employees">
    <Type Name="tbl_Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="AvailableLeaves" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_Employee_tbl_User" Member="tbl_Users" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="tbl_User" />
      <Association Name="tbl_Employee_tbl_DeductionsLog" Member="tbl_DeductionsLogs" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="tbl_DeductionsLog" />
      <Association Name="tbl_Employee_tbl_Payroll" Member="tbl_Payrolls" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="tbl_Payroll" />
      <Association Name="tbl_EmployeeType_tbl_Employee" Member="tbl_EmployeeType" ThisKey="EmployeeTypeID" OtherKey="EmployeeTypesID" Type="tbl_EmployeeType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_EmployeeTypes" Member="tbl_EmployeeTypes">
    <Type Name="tbl_EmployeeType">
      <Column Name="EmployeeTypesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeNameTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalaryRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="tbl_EmployeeType_tbl_Employee" Member="tbl_Employees" ThisKey="EmployeeTypesID" OtherKey="EmployeeTypeID" Type="tbl_Employee" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_Payroll" Member="tbl_Payrolls">
    <Type Name="tbl_Payroll">
      <Column Name="PayrollID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDeductions" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NumberOfHoursWorked" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeWorked" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimePay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Netpay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="tbl_Employee_tbl_Payroll" Member="tbl_Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="tbl_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_checkLogin" Method="sp_checkLogin">
    <Parameter Name="username" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_checkLoginResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SecretQuestion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecretAnswer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>