//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJLS_FOODS_PAYROLL_SYSTEM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PSYCHO;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=True")]
        public string CJLSFOODSPAYROLLConnectionString {
            get {
                return ((string)(this["CJLSFOODSPAYROLLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEIL2;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=True")]
        public string CJLSFOODSPAYROLLConnectionString1 {
            get {
                return ((string)(this["CJLSFOODSPAYROLLConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PSYCHO;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=True")]
        public string CJLSFOODSPAYROLLConnectionString2 {
            get {
                return ((string)(this["CJLSFOODSPAYROLLConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NEIL\\SQLEXPRESS;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=" +
            "True")]
        public string CJLSFOODSPAYROLLConnectionString3 {
            get {
                return ((string)(this["CJLSFOODSPAYROLLConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G3UC9K4;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=" +
            "True")]
        public string CJLSFOODSPAYROLLConnectionString4 {
            get {
                return ((string)(this["CJLSFOODSPAYROLLConnectionString4"]));
            }
        }
    }
}
