<?xml version="1.0" encoding="utf-8"?><Database Name="CJLSFOODSPAYROLL" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NEIL\SQLEXPRESS;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=True" SettingsObjectName="CJLS_FOODS_PAYROLL_SYSTEM.Properties.Settings" SettingsPropertyName="CJLSFOODSPAYROLLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Attendance" Member="Attendances">
    <Type Name="Attendance">
      <Column Name="AttendanceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegularHoursWorked" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OverTimeHoursWorked" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AttendanceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PayrollDetailsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinutesLate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Attendance_Deduction" Member="Deductions" ThisKey="AttendanceID" OtherKey="AttendanceID" Type="Deduction" />
      <Association Name="PayrollDetail_Attendance" Member="PayrollDetail" ThisKey="PayrollDetailsID" OtherKey="PayrollDetailID" Type="PayrollDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecretQuestion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecretAnswer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contribution" Member="Contributions">
    <Type Name="Contribution">
      <Column Name="ContributionLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContributionTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PayrollDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ContributionType_Contribution" Member="ContributionType" ThisKey="ContributionTypeID" OtherKey="ContributionTypeID" Type="ContributionType" IsForeignKey="true" />
      <Association Name="PayrollDetail_Contribution" Member="PayrollDetail" ThisKey="PayrollDetailID" OtherKey="PayrollDetailID" Type="PayrollDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContributionType" Member="ContributionTypes">
    <Type Name="ContributionType">
      <Column Name="ContributionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PercentageRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ContributionType_Contribution" Member="Contributions" ThisKey="ContributionTypeID" OtherKey="ContributionTypeID" Type="Contribution" />
    </Type>
  </Table>
  <Table Name="dbo.Deduction" Member="Deductions">
    <Type Name="Deduction">
      <Column Name="DeductionsLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeductionTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="AttendanceID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Attendance_Deduction" Member="Attendance" ThisKey="AttendanceID" OtherKey="AttendanceID" Type="Attendance" IsForeignKey="true" />
      <Association Name="DeductionsType_Deduction" Member="DeductionsType" ThisKey="DeductionTypeID" OtherKey="DeductionTypeID" Type="DeductionsType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeductionsTypes" Member="DeductionsTypes">
    <Type Name="DeductionsType">
      <Column Name="DeductionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeductionReferenceId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DeductionsType_Deduction" Member="Deductions" ThisKey="DeductionTypeID" OtherKey="DeductionTypeID" Type="Deduction" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="AvailableLeaves" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HourlyRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DailyRequiredHours" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="MonthlySalary" Type="System.Double" DbType="Float NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SSSID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PagIbigID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhilhealthID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TINID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsPhilhealthActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSSSActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsIncomeTaxActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsPagibigActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Employee_Leave" Member="Leaves" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Leave" />
      <Association Name="Employee_PayrollDetail" Member="PayrollDetails" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="PayrollDetail" />
      <Association Name="EmployeeType_Employee" Member="EmployeeType" ThisKey="EmployeeTypeID" OtherKey="EmployeeTypeID" Type="EmployeeType" IsForeignKey="true" />
      <Association Name="PayrollGroup_Employee" Member="PayrollGroup" ThisKey="EmployeeGroupID" OtherKey="PayrollGroupID" Type="PayrollGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeType" Member="EmployeeTypes">
    <Type Name="EmployeeType">
      <Column Name="EmployeeTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="EmployeeType_Employee" Member="Employees" ThisKey="EmployeeTypeID" OtherKey="EmployeeTypeID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Leave" Member="Leaves">
    <Type Name="Leave">
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeaveID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ApprovalStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Employee_Leave" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll" Member="Payrolls">
    <Type Name="Payroll">
      <Column Name="PayrollID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PayrollGroupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDays" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Payroll_PayrollDetail" Member="PayrollDetails" ThisKey="PayrollID" OtherKey="PayrollID" Type="PayrollDetail" />
      <Association Name="PayrollGroup_Payroll" Member="PayrollGroup" ThisKey="PayrollGroupID" OtherKey="PayrollGroupID" Type="PayrollGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayrollDetail" Member="PayrollDetails">
    <Type Name="PayrollDetail">
      <Column Name="PayrollDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PayrollID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDeductions" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalRegularHours" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalOverTimeHours" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="OvertimePay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="NetPay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GrossPay" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TotalContributions" Type="System.Double" DbType="Float" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="PayrollDetail_Attendance" Member="Attendances" ThisKey="PayrollDetailID" OtherKey="PayrollDetailsID" Type="Attendance" />
      <Association Name="PayrollDetail_Contribution" Member="Contributions" ThisKey="PayrollDetailID" OtherKey="PayrollDetailID" Type="Contribution" />
      <Association Name="Employee_PayrollDetail" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Payroll_PayrollDetail" Member="Payroll" ThisKey="PayrollID" OtherKey="PayrollID" Type="Payroll" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PayrollGroup" Member="PayrollGroups">
    <Type Name="PayrollGroup">
      <Column Name="PayrollGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="PayrollGroup_Employee" Member="Employees" ThisKey="PayrollGroupID" OtherKey="EmployeeGroupID" Type="Employee" />
      <Association Name="PayrollGroup_Payroll" Member="Payrolls" ThisKey="PayrollGroupID" OtherKey="PayrollGroupID" Type="Payroll" />
    </Type>
  </Table>
</Database>