<?xml version="1.0" encoding="utf-8"?><Database Name="CJLSFOODSPAYROLL" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NEIL\SQLEXPRESS;Initial Catalog=CJLSFOODSPAYROLL;Integrated Security=True" SettingsObjectName="CJLS_FOODS_PAYROLL_SYSTEM.Properties.Settings" SettingsPropertyName="CJLSFOODSPAYROLLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Attendance" Member="Attendances">
    <Type Name="Attendance">
      <Column Name="AttendanceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumOfHoursWorked" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OverWorkedHours" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Employee_Attendance" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecretQuestion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SecretAnswer" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeductionLogs" Member="DeductionLogs">
    <Type Name="DeductionLog">
      <Column Name="DeductionsLogId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeductionTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DateApplied" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DeductionsType_DeductionLog" Member="DeductionsType" ThisKey="DeductionTypeID" OtherKey="DeductionTypeID" Type="DeductionsType" IsForeignKey="true" />
      <Association Name="Employee_DeductionLog" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeductionsTypes" Member="DeductionsTypes">
    <Type Name="DeductionsType">
      <Column Name="DeductionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeductionName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeductionReferenceId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DeductionsType_DeductionLog" Member="DeductionLogs" ThisKey="DeductionTypeID" OtherKey="DeductionTypeID" Type="DeductionLog" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="AvailableLeaves" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalaryRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SSSID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PagIbigID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PhilhealthID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TINID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Employee_Attendance" Member="Attendances" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Attendance" />
      <Association Name="Employee_DeductionLog" Member="DeductionLogs" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="DeductionLog" />
      <Association Name="Employee_Leave" Member="Leaves" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Leave" />
      <Association Name="Employee_Payroll" Member="Payrolls" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Payroll" />
      <Association Name="EmployeeType_Employee" Member="EmployeeType" ThisKey="EmployeeTypeID" OtherKey="EmployeeTypesID" Type="EmployeeType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeTypes" Member="EmployeeTypes">
    <Type Name="EmployeeType">
      <Column Name="EmployeeTypesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeNameTitle" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SalaryRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="EmployeeType_Employee" Member="Employees" ThisKey="EmployeeTypesID" OtherKey="EmployeeTypeID" Type="Employee" />
    </Type>
  </Table>
  <Table Name="dbo.Leave" Member="Leaves">
    <Type Name="Leave">
      <Column Name="LeaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Leave" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payrolls" Member="Payrolls">
    <Type Name="Payroll">
      <Column Name="PayrollID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalDeductions" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalContributions" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NumberOfHoursWorked" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimeWorked" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OvertimePay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Netpay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Employee_Payroll" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>