#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJLS_FOODS_PAYROLL_SYSTEM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CJLSFOODSPAYROLL")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAttendance(Attendance instance);
    partial void UpdateAttendance(Attendance instance);
    partial void DeleteAttendance(Attendance instance);
    partial void InsertDeduction(Deduction instance);
    partial void UpdateDeduction(Deduction instance);
    partial void DeleteDeduction(Deduction instance);
    partial void InsertDeductionsType(DeductionsType instance);
    partial void UpdateDeductionsType(DeductionsType instance);
    partial void DeleteDeductionsType(DeductionsType instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertEmployeeType(EmployeeType instance);
    partial void UpdateEmployeeType(EmployeeType instance);
    partial void DeleteEmployeeType(EmployeeType instance);
    partial void InsertPayroll(Payroll instance);
    partial void UpdatePayroll(Payroll instance);
    partial void DeletePayroll(Payroll instance);
    partial void InsertPayrollDetail(PayrollDetail instance);
    partial void UpdatePayrollDetail(PayrollDetail instance);
    partial void DeletePayrollDetail(PayrollDetail instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::CJLS_FOODS_PAYROLL_SYSTEM.Properties.Settings.Default.CJLSFOODSPAYROLLConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Attendance> Attendances
		{
			get
			{
				return this.GetTable<Attendance>();
			}
		}
		
		public System.Data.Linq.Table<Deduction> Deductions
		{
			get
			{
				return this.GetTable<Deduction>();
			}
		}
		
		public System.Data.Linq.Table<DeductionsType> DeductionsTypes
		{
			get
			{
				return this.GetTable<DeductionsType>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeType> EmployeeTypes
		{
			get
			{
				return this.GetTable<EmployeeType>();
			}
		}
		
		public System.Data.Linq.Table<Leave> Leaves
		{
			get
			{
				return this.GetTable<Leave>();
			}
		}
		
		public System.Data.Linq.Table<Payroll> Payrolls
		{
			get
			{
				return this.GetTable<Payroll>();
			}
		}
		
		public System.Data.Linq.Table<PayrollDetail> PayrollDetails
		{
			get
			{
				return this.GetTable<PayrollDetail>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Attendance")]
	public partial class Attendance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _AttendanceDate;
		
		private int _RegularHoursWorked;
		
		private int _OverTimeHoursWorked;
		
		private int _AttendanceID;
		
		private System.Nullable<int> _PayrollDetailsID;
		
		private EntitySet<Deduction> _Deductions;
		
		private EntityRef<PayrollDetail> _PayrollDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAttendanceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAttendanceDateChanged();
    partial void OnRegularHoursWorkedChanging(int value);
    partial void OnRegularHoursWorkedChanged();
    partial void OnOverTimeHoursWorkedChanging(int value);
    partial void OnOverTimeHoursWorkedChanged();
    partial void OnAttendanceIDChanging(int value);
    partial void OnAttendanceIDChanged();
    partial void OnPayrollDetailsIDChanging(System.Nullable<int> value);
    partial void OnPayrollDetailsIDChanged();
    #endregion
		
		public Attendance()
		{
			this._Deductions = new EntitySet<Deduction>(new Action<Deduction>(this.attach_Deductions), new Action<Deduction>(this.detach_Deductions));
			this._PayrollDetail = default(EntityRef<PayrollDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AttendanceDate
		{
			get
			{
				return this._AttendanceDate;
			}
			set
			{
				if ((this._AttendanceDate != value))
				{
					this.OnAttendanceDateChanging(value);
					this.SendPropertyChanging();
					this._AttendanceDate = value;
					this.SendPropertyChanged("AttendanceDate");
					this.OnAttendanceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegularHoursWorked", DbType="Int NOT NULL")]
		public int RegularHoursWorked
		{
			get
			{
				return this._RegularHoursWorked;
			}
			set
			{
				if ((this._RegularHoursWorked != value))
				{
					this.OnRegularHoursWorkedChanging(value);
					this.SendPropertyChanging();
					this._RegularHoursWorked = value;
					this.SendPropertyChanged("RegularHoursWorked");
					this.OnRegularHoursWorkedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OverTimeHoursWorked", DbType="Int NOT NULL")]
		public int OverTimeHoursWorked
		{
			get
			{
				return this._OverTimeHoursWorked;
			}
			set
			{
				if ((this._OverTimeHoursWorked != value))
				{
					this.OnOverTimeHoursWorkedChanging(value);
					this.SendPropertyChanging();
					this._OverTimeHoursWorked = value;
					this.SendPropertyChanged("OverTimeHoursWorked");
					this.OnOverTimeHoursWorkedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AttendanceID
		{
			get
			{
				return this._AttendanceID;
			}
			set
			{
				if ((this._AttendanceID != value))
				{
					this.OnAttendanceIDChanging(value);
					this.SendPropertyChanging();
					this._AttendanceID = value;
					this.SendPropertyChanged("AttendanceID");
					this.OnAttendanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollDetailsID", DbType="Int")]
		public System.Nullable<int> PayrollDetailsID
		{
			get
			{
				return this._PayrollDetailsID;
			}
			set
			{
				if ((this._PayrollDetailsID != value))
				{
					if (this._PayrollDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPayrollDetailsIDChanging(value);
					this.SendPropertyChanging();
					this._PayrollDetailsID = value;
					this.SendPropertyChanged("PayrollDetailsID");
					this.OnPayrollDetailsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Attendance_Deduction", Storage="_Deductions", ThisKey="AttendanceID", OtherKey="AttendanceID")]
		public EntitySet<Deduction> Deductions
		{
			get
			{
				return this._Deductions;
			}
			set
			{
				this._Deductions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PayrollDetail_Attendance", Storage="_PayrollDetail", ThisKey="PayrollDetailsID", OtherKey="PayrollDetailID", IsForeignKey=true)]
		public PayrollDetail PayrollDetail
		{
			get
			{
				return this._PayrollDetail.Entity;
			}
			set
			{
				PayrollDetail previousValue = this._PayrollDetail.Entity;
				if (((previousValue != value) 
							|| (this._PayrollDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PayrollDetail.Entity = null;
						previousValue.Attendances.Remove(this);
					}
					this._PayrollDetail.Entity = value;
					if ((value != null))
					{
						value.Attendances.Add(this);
						this._PayrollDetailsID = value.PayrollDetailID;
					}
					else
					{
						this._PayrollDetailsID = default(Nullable<int>);
					}
					this.SendPropertyChanged("PayrollDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Deductions(Deduction entity)
		{
			this.SendPropertyChanging();
			entity.Attendance = this;
		}
		
		private void detach_Deductions(Deduction entity)
		{
			this.SendPropertyChanging();
			entity.Attendance = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Deduction")]
	public partial class Deduction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DeductionsLogId;
		
		private System.Nullable<int> _DeductionTypeID;
		
		private System.Nullable<double> _Amount;
		
		private System.Nullable<int> _AttendanceID;
		
		private EntityRef<Attendance> _Attendance;
		
		private EntityRef<DeductionsType> _DeductionsType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeductionsLogIdChanging(int value);
    partial void OnDeductionsLogIdChanged();
    partial void OnDeductionTypeIDChanging(System.Nullable<int> value);
    partial void OnDeductionTypeIDChanged();
    partial void OnAmountChanging(System.Nullable<double> value);
    partial void OnAmountChanged();
    partial void OnAttendanceIDChanging(System.Nullable<int> value);
    partial void OnAttendanceIDChanged();
    #endregion
		
		public Deduction()
		{
			this._Attendance = default(EntityRef<Attendance>);
			this._DeductionsType = default(EntityRef<DeductionsType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeductionsLogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DeductionsLogId
		{
			get
			{
				return this._DeductionsLogId;
			}
			set
			{
				if ((this._DeductionsLogId != value))
				{
					this.OnDeductionsLogIdChanging(value);
					this.SendPropertyChanging();
					this._DeductionsLogId = value;
					this.SendPropertyChanged("DeductionsLogId");
					this.OnDeductionsLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeductionTypeID", DbType="Int")]
		public System.Nullable<int> DeductionTypeID
		{
			get
			{
				return this._DeductionTypeID;
			}
			set
			{
				if ((this._DeductionTypeID != value))
				{
					if (this._DeductionsType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDeductionTypeIDChanging(value);
					this.SendPropertyChanging();
					this._DeductionTypeID = value;
					this.SendPropertyChanged("DeductionTypeID");
					this.OnDeductionTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Float")]
		public System.Nullable<double> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendanceID", DbType="Int")]
		public System.Nullable<int> AttendanceID
		{
			get
			{
				return this._AttendanceID;
			}
			set
			{
				if ((this._AttendanceID != value))
				{
					if (this._Attendance.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAttendanceIDChanging(value);
					this.SendPropertyChanging();
					this._AttendanceID = value;
					this.SendPropertyChanged("AttendanceID");
					this.OnAttendanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Attendance_Deduction", Storage="_Attendance", ThisKey="AttendanceID", OtherKey="AttendanceID", IsForeignKey=true)]
		public Attendance Attendance
		{
			get
			{
				return this._Attendance.Entity;
			}
			set
			{
				Attendance previousValue = this._Attendance.Entity;
				if (((previousValue != value) 
							|| (this._Attendance.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Attendance.Entity = null;
						previousValue.Deductions.Remove(this);
					}
					this._Attendance.Entity = value;
					if ((value != null))
					{
						value.Deductions.Add(this);
						this._AttendanceID = value.AttendanceID;
					}
					else
					{
						this._AttendanceID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Attendance");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeductionsType_Deduction", Storage="_DeductionsType", ThisKey="DeductionTypeID", OtherKey="DeductionTypeID", IsForeignKey=true)]
		public DeductionsType DeductionsType
		{
			get
			{
				return this._DeductionsType.Entity;
			}
			set
			{
				DeductionsType previousValue = this._DeductionsType.Entity;
				if (((previousValue != value) 
							|| (this._DeductionsType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeductionsType.Entity = null;
						previousValue.Deductions.Remove(this);
					}
					this._DeductionsType.Entity = value;
					if ((value != null))
					{
						value.Deductions.Add(this);
						this._DeductionTypeID = value.DeductionTypeID;
					}
					else
					{
						this._DeductionTypeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("DeductionsType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeductionsTypes")]
	public partial class DeductionsType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DeductionTypeID;
		
		private string _DeductionName;
		
		private string _DeductionReferenceId;
		
		private EntitySet<Deduction> _Deductions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeductionTypeIDChanging(int value);
    partial void OnDeductionTypeIDChanged();
    partial void OnDeductionNameChanging(string value);
    partial void OnDeductionNameChanged();
    partial void OnDeductionReferenceIdChanging(string value);
    partial void OnDeductionReferenceIdChanged();
    #endregion
		
		public DeductionsType()
		{
			this._Deductions = new EntitySet<Deduction>(new Action<Deduction>(this.attach_Deductions), new Action<Deduction>(this.detach_Deductions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeductionTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DeductionTypeID
		{
			get
			{
				return this._DeductionTypeID;
			}
			set
			{
				if ((this._DeductionTypeID != value))
				{
					this.OnDeductionTypeIDChanging(value);
					this.SendPropertyChanging();
					this._DeductionTypeID = value;
					this.SendPropertyChanged("DeductionTypeID");
					this.OnDeductionTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeductionName", DbType="VarChar(50)")]
		public string DeductionName
		{
			get
			{
				return this._DeductionName;
			}
			set
			{
				if ((this._DeductionName != value))
				{
					this.OnDeductionNameChanging(value);
					this.SendPropertyChanging();
					this._DeductionName = value;
					this.SendPropertyChanged("DeductionName");
					this.OnDeductionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeductionReferenceId", DbType="VarChar(50)")]
		public string DeductionReferenceId
		{
			get
			{
				return this._DeductionReferenceId;
			}
			set
			{
				if ((this._DeductionReferenceId != value))
				{
					this.OnDeductionReferenceIdChanging(value);
					this.SendPropertyChanging();
					this._DeductionReferenceId = value;
					this.SendPropertyChanged("DeductionReferenceId");
					this.OnDeductionReferenceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DeductionsType_Deduction", Storage="_Deductions", ThisKey="DeductionTypeID", OtherKey="DeductionTypeID")]
		public EntitySet<Deduction> Deductions
		{
			get
			{
				return this._Deductions;
			}
			set
			{
				this._Deductions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Deductions(Deduction entity)
		{
			this.SendPropertyChanging();
			entity.DeductionsType = this;
		}
		
		private void detach_Deductions(Deduction entity)
		{
			this.SendPropertyChanging();
			entity.DeductionsType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmployeeID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private System.Nullable<int> _Age;
		
		private string _ContactNumber;
		
		private string _Address;
		
		private string _Gender;
		
		private System.Nullable<int> _AvailableLeaves;
		
		private System.Nullable<int> _EmployeeTypeID;
		
		private string _MiddleName;
		
		private System.Nullable<double> _HourlyRate;
		
		private string _SSSID;
		
		private string _PagIbigID;
		
		private string _PhilhealthID;
		
		private string _TINID;
		
		private string _Branch;
		
		private string _Status;
		
		private EntitySet<PayrollDetail> _PayrollDetails;
		
		private EntityRef<EmployeeType> _EmployeeType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeIDChanging(int value);
    partial void OnEmployeeIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnAvailableLeavesChanging(System.Nullable<int> value);
    partial void OnAvailableLeavesChanged();
    partial void OnEmployeeTypeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeTypeIDChanged();
    partial void OnMiddleNameChanging(string value);
    partial void OnMiddleNameChanged();
    partial void OnHourlyRateChanging(System.Nullable<double> value);
    partial void OnHourlyRateChanged();
    partial void OnSSSIDChanging(string value);
    partial void OnSSSIDChanged();
    partial void OnPagIbigIDChanging(string value);
    partial void OnPagIbigIDChanged();
    partial void OnPhilhealthIDChanging(string value);
    partial void OnPhilhealthIDChanged();
    partial void OnTINIDChanging(string value);
    partial void OnTINIDChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Employee()
		{
			this._PayrollDetails = new EntitySet<PayrollDetail>(new Action<PayrollDetail>(this.attach_PayrollDetails), new Action<PayrollDetail>(this.detach_PayrollDetails));
			this._EmployeeType = default(EntityRef<EmployeeType>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNumber", DbType="VarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(25)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableLeaves", DbType="Int")]
		public System.Nullable<int> AvailableLeaves
		{
			get
			{
				return this._AvailableLeaves;
			}
			set
			{
				if ((this._AvailableLeaves != value))
				{
					this.OnAvailableLeavesChanging(value);
					this.SendPropertyChanging();
					this._AvailableLeaves = value;
					this.SendPropertyChanged("AvailableLeaves");
					this.OnAvailableLeavesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypeID", DbType="Int")]
		public System.Nullable<int> EmployeeTypeID
		{
			get
			{
				return this._EmployeeTypeID;
			}
			set
			{
				if ((this._EmployeeTypeID != value))
				{
					if (this._EmployeeType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeTypeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeTypeID = value;
					this.SendPropertyChanged("EmployeeTypeID");
					this.OnEmployeeTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MiddleName", DbType="VarChar(50)")]
		public string MiddleName
		{
			get
			{
				return this._MiddleName;
			}
			set
			{
				if ((this._MiddleName != value))
				{
					this.OnMiddleNameChanging(value);
					this.SendPropertyChanging();
					this._MiddleName = value;
					this.SendPropertyChanged("MiddleName");
					this.OnMiddleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HourlyRate", DbType="Float")]
		public System.Nullable<double> HourlyRate
		{
			get
			{
				return this._HourlyRate;
			}
			set
			{
				if ((this._HourlyRate != value))
				{
					this.OnHourlyRateChanging(value);
					this.SendPropertyChanging();
					this._HourlyRate = value;
					this.SendPropertyChanged("HourlyRate");
					this.OnHourlyRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SSSID", DbType="VarChar(50)")]
		public string SSSID
		{
			get
			{
				return this._SSSID;
			}
			set
			{
				if ((this._SSSID != value))
				{
					this.OnSSSIDChanging(value);
					this.SendPropertyChanging();
					this._SSSID = value;
					this.SendPropertyChanged("SSSID");
					this.OnSSSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagIbigID", DbType="VarChar(50)")]
		public string PagIbigID
		{
			get
			{
				return this._PagIbigID;
			}
			set
			{
				if ((this._PagIbigID != value))
				{
					this.OnPagIbigIDChanging(value);
					this.SendPropertyChanging();
					this._PagIbigID = value;
					this.SendPropertyChanged("PagIbigID");
					this.OnPagIbigIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhilhealthID", DbType="VarChar(50)")]
		public string PhilhealthID
		{
			get
			{
				return this._PhilhealthID;
			}
			set
			{
				if ((this._PhilhealthID != value))
				{
					this.OnPhilhealthIDChanging(value);
					this.SendPropertyChanging();
					this._PhilhealthID = value;
					this.SendPropertyChanged("PhilhealthID");
					this.OnPhilhealthIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINID", DbType="VarChar(50)")]
		public string TINID
		{
			get
			{
				return this._TINID;
			}
			set
			{
				if ((this._TINID != value))
				{
					this.OnTINIDChanging(value);
					this.SendPropertyChanging();
					this._TINID = value;
					this.SendPropertyChanged("TINID");
					this.OnTINIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="VarChar(50)")]
		public string Branch
		{
			get
			{
				return this._Branch;
			}
			set
			{
				if ((this._Branch != value))
				{
					this.OnBranchChanging(value);
					this.SendPropertyChanging();
					this._Branch = value;
					this.SendPropertyChanged("Branch");
					this.OnBranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_PayrollDetail", Storage="_PayrollDetails", ThisKey="EmployeeID", OtherKey="EmployeeID")]
		public EntitySet<PayrollDetail> PayrollDetails
		{
			get
			{
				return this._PayrollDetails;
			}
			set
			{
				this._PayrollDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EmployeeType_Employee", Storage="_EmployeeType", ThisKey="EmployeeTypeID", OtherKey="EmployeeTypesID", IsForeignKey=true)]
		public EmployeeType EmployeeType
		{
			get
			{
				return this._EmployeeType.Entity;
			}
			set
			{
				EmployeeType previousValue = this._EmployeeType.Entity;
				if (((previousValue != value) 
							|| (this._EmployeeType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EmployeeType.Entity = null;
						previousValue.Employees.Remove(this);
					}
					this._EmployeeType.Entity = value;
					if ((value != null))
					{
						value.Employees.Add(this);
						this._EmployeeTypeID = value.EmployeeTypesID;
					}
					else
					{
						this._EmployeeTypeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("EmployeeType");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PayrollDetails(PayrollDetail entity)
		{
			this.SendPropertyChanging();
			entity.Employee = this;
		}
		
		private void detach_PayrollDetails(PayrollDetail entity)
		{
			this.SendPropertyChanging();
			entity.Employee = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeeTypes")]
	public partial class EmployeeType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmployeeTypesID;
		
		private string _EmployeeNameTitle;
		
		private System.Nullable<double> _SalaryRate;
		
		private EntitySet<Employee> _Employees;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployeeTypesIDChanging(int value);
    partial void OnEmployeeTypesIDChanged();
    partial void OnEmployeeNameTitleChanging(string value);
    partial void OnEmployeeNameTitleChanged();
    partial void OnSalaryRateChanging(System.Nullable<double> value);
    partial void OnSalaryRateChanged();
    #endregion
		
		public EmployeeType()
		{
			this._Employees = new EntitySet<Employee>(new Action<Employee>(this.attach_Employees), new Action<Employee>(this.detach_Employees));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeTypesID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmployeeTypesID
		{
			get
			{
				return this._EmployeeTypesID;
			}
			set
			{
				if ((this._EmployeeTypesID != value))
				{
					this.OnEmployeeTypesIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeTypesID = value;
					this.SendPropertyChanged("EmployeeTypesID");
					this.OnEmployeeTypesIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeNameTitle", DbType="VarChar(50)")]
		public string EmployeeNameTitle
		{
			get
			{
				return this._EmployeeNameTitle;
			}
			set
			{
				if ((this._EmployeeNameTitle != value))
				{
					this.OnEmployeeNameTitleChanging(value);
					this.SendPropertyChanging();
					this._EmployeeNameTitle = value;
					this.SendPropertyChanged("EmployeeNameTitle");
					this.OnEmployeeNameTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SalaryRate", DbType="Float")]
		public System.Nullable<double> SalaryRate
		{
			get
			{
				return this._SalaryRate;
			}
			set
			{
				if ((this._SalaryRate != value))
				{
					this.OnSalaryRateChanging(value);
					this.SendPropertyChanging();
					this._SalaryRate = value;
					this.SendPropertyChanged("SalaryRate");
					this.OnSalaryRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EmployeeType_Employee", Storage="_Employees", ThisKey="EmployeeTypesID", OtherKey="EmployeeTypeID")]
		public EntitySet<Employee> Employees
		{
			get
			{
				return this._Employees;
			}
			set
			{
				this._Employees.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Employees(Employee entity)
		{
			this.SendPropertyChanging();
			entity.EmployeeType = this;
		}
		
		private void detach_Employees(Employee entity)
		{
			this.SendPropertyChanging();
			entity.EmployeeType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Leave")]
	public partial class Leave
	{
		
		private System.Nullable<System.DateTime> _LeaveDate;
		
		private System.Nullable<int> _EmployeeID;
		
		public Leave()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LeaveDate
		{
			get
			{
				return this._LeaveDate;
			}
			set
			{
				if ((this._LeaveDate != value))
				{
					this._LeaveDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this._EmployeeID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Payroll")]
	public partial class Payroll : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PayrollID;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private EntitySet<PayrollDetail> _PayrollDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayrollIDChanging(int value);
    partial void OnPayrollIDChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    #endregion
		
		public Payroll()
		{
			this._PayrollDetails = new EntitySet<PayrollDetail>(new Action<PayrollDetail>(this.attach_PayrollDetails), new Action<PayrollDetail>(this.detach_PayrollDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PayrollID
		{
			get
			{
				return this._PayrollID;
			}
			set
			{
				if ((this._PayrollID != value))
				{
					this.OnPayrollIDChanging(value);
					this.SendPropertyChanging();
					this._PayrollID = value;
					this.SendPropertyChanged("PayrollID");
					this.OnPayrollIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Payroll_PayrollDetail", Storage="_PayrollDetails", ThisKey="PayrollID", OtherKey="PayrollID")]
		public EntitySet<PayrollDetail> PayrollDetails
		{
			get
			{
				return this._PayrollDetails;
			}
			set
			{
				this._PayrollDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PayrollDetails(PayrollDetail entity)
		{
			this.SendPropertyChanging();
			entity.Payroll = this;
		}
		
		private void detach_PayrollDetails(PayrollDetail entity)
		{
			this.SendPropertyChanging();
			entity.Payroll = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PayrollDetail")]
	public partial class PayrollDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PayrollDetailID;
		
		private System.Nullable<int> _PayrollID;
		
		private System.Nullable<int> _EmployeeID;
		
		private System.Nullable<double> _TotalDeductions;
		
		private System.Nullable<double> _TotalContributions;
		
		private System.Nullable<double> _TotalRegularHours;
		
		private System.Nullable<double> _TotalOverTimeHours;
		
		private System.Nullable<double> _OvertimePay;
		
		private System.Nullable<double> _NetPay;
		
		private System.Nullable<double> _GrossPay;
		
		private EntitySet<Attendance> _Attendances;
		
		private EntityRef<Employee> _Employee;
		
		private EntityRef<Payroll> _Payroll;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayrollDetailIDChanging(int value);
    partial void OnPayrollDetailIDChanged();
    partial void OnPayrollIDChanging(System.Nullable<int> value);
    partial void OnPayrollIDChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    partial void OnTotalDeductionsChanging(System.Nullable<double> value);
    partial void OnTotalDeductionsChanged();
    partial void OnTotalContributionsChanging(System.Nullable<double> value);
    partial void OnTotalContributionsChanged();
    partial void OnTotalRegularHoursChanging(System.Nullable<double> value);
    partial void OnTotalRegularHoursChanged();
    partial void OnTotalOverTimeHoursChanging(System.Nullable<double> value);
    partial void OnTotalOverTimeHoursChanged();
    partial void OnOvertimePayChanging(System.Nullable<double> value);
    partial void OnOvertimePayChanged();
    partial void OnNetPayChanging(System.Nullable<double> value);
    partial void OnNetPayChanged();
    partial void OnGrossPayChanging(System.Nullable<double> value);
    partial void OnGrossPayChanged();
    #endregion
		
		public PayrollDetail()
		{
			this._Attendances = new EntitySet<Attendance>(new Action<Attendance>(this.attach_Attendances), new Action<Attendance>(this.detach_Attendances));
			this._Employee = default(EntityRef<Employee>);
			this._Payroll = default(EntityRef<Payroll>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollDetailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PayrollDetailID
		{
			get
			{
				return this._PayrollDetailID;
			}
			set
			{
				if ((this._PayrollDetailID != value))
				{
					this.OnPayrollDetailIDChanging(value);
					this.SendPropertyChanging();
					this._PayrollDetailID = value;
					this.SendPropertyChanged("PayrollDetailID");
					this.OnPayrollDetailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollID", DbType="Int")]
		public System.Nullable<int> PayrollID
		{
			get
			{
				return this._PayrollID;
			}
			set
			{
				if ((this._PayrollID != value))
				{
					if (this._Payroll.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPayrollIDChanging(value);
					this.SendPropertyChanging();
					this._PayrollID = value;
					this.SendPropertyChanged("PayrollID");
					this.OnPayrollIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					if (this._Employee.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDeductions", DbType="Float")]
		public System.Nullable<double> TotalDeductions
		{
			get
			{
				return this._TotalDeductions;
			}
			set
			{
				if ((this._TotalDeductions != value))
				{
					this.OnTotalDeductionsChanging(value);
					this.SendPropertyChanging();
					this._TotalDeductions = value;
					this.SendPropertyChanged("TotalDeductions");
					this.OnTotalDeductionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalContributions", DbType="Float")]
		public System.Nullable<double> TotalContributions
		{
			get
			{
				return this._TotalContributions;
			}
			set
			{
				if ((this._TotalContributions != value))
				{
					this.OnTotalContributionsChanging(value);
					this.SendPropertyChanging();
					this._TotalContributions = value;
					this.SendPropertyChanged("TotalContributions");
					this.OnTotalContributionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalRegularHours", DbType="Float")]
		public System.Nullable<double> TotalRegularHours
		{
			get
			{
				return this._TotalRegularHours;
			}
			set
			{
				if ((this._TotalRegularHours != value))
				{
					this.OnTotalRegularHoursChanging(value);
					this.SendPropertyChanging();
					this._TotalRegularHours = value;
					this.SendPropertyChanged("TotalRegularHours");
					this.OnTotalRegularHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalOverTimeHours", DbType="Float")]
		public System.Nullable<double> TotalOverTimeHours
		{
			get
			{
				return this._TotalOverTimeHours;
			}
			set
			{
				if ((this._TotalOverTimeHours != value))
				{
					this.OnTotalOverTimeHoursChanging(value);
					this.SendPropertyChanging();
					this._TotalOverTimeHours = value;
					this.SendPropertyChanged("TotalOverTimeHours");
					this.OnTotalOverTimeHoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OvertimePay", DbType="Float")]
		public System.Nullable<double> OvertimePay
		{
			get
			{
				return this._OvertimePay;
			}
			set
			{
				if ((this._OvertimePay != value))
				{
					this.OnOvertimePayChanging(value);
					this.SendPropertyChanging();
					this._OvertimePay = value;
					this.SendPropertyChanged("OvertimePay");
					this.OnOvertimePayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetPay", DbType="Float")]
		public System.Nullable<double> NetPay
		{
			get
			{
				return this._NetPay;
			}
			set
			{
				if ((this._NetPay != value))
				{
					this.OnNetPayChanging(value);
					this.SendPropertyChanging();
					this._NetPay = value;
					this.SendPropertyChanged("NetPay");
					this.OnNetPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrossPay", DbType="Float")]
		public System.Nullable<double> GrossPay
		{
			get
			{
				return this._GrossPay;
			}
			set
			{
				if ((this._GrossPay != value))
				{
					this.OnGrossPayChanging(value);
					this.SendPropertyChanging();
					this._GrossPay = value;
					this.SendPropertyChanged("GrossPay");
					this.OnGrossPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PayrollDetail_Attendance", Storage="_Attendances", ThisKey="PayrollDetailID", OtherKey="PayrollDetailsID")]
		public EntitySet<Attendance> Attendances
		{
			get
			{
				return this._Attendances;
			}
			set
			{
				this._Attendances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employee_PayrollDetail", Storage="_Employee", ThisKey="EmployeeID", OtherKey="EmployeeID", IsForeignKey=true)]
		public Employee Employee
		{
			get
			{
				return this._Employee.Entity;
			}
			set
			{
				Employee previousValue = this._Employee.Entity;
				if (((previousValue != value) 
							|| (this._Employee.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employee.Entity = null;
						previousValue.PayrollDetails.Remove(this);
					}
					this._Employee.Entity = value;
					if ((value != null))
					{
						value.PayrollDetails.Add(this);
						this._EmployeeID = value.EmployeeID;
					}
					else
					{
						this._EmployeeID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Employee");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Payroll_PayrollDetail", Storage="_Payroll", ThisKey="PayrollID", OtherKey="PayrollID", IsForeignKey=true)]
		public Payroll Payroll
		{
			get
			{
				return this._Payroll.Entity;
			}
			set
			{
				Payroll previousValue = this._Payroll.Entity;
				if (((previousValue != value) 
							|| (this._Payroll.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Payroll.Entity = null;
						previousValue.PayrollDetails.Remove(this);
					}
					this._Payroll.Entity = value;
					if ((value != null))
					{
						value.PayrollDetails.Add(this);
						this._PayrollID = value.PayrollID;
					}
					else
					{
						this._PayrollID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Payroll");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Attendances(Attendance entity)
		{
			this.SendPropertyChanging();
			entity.PayrollDetail = this;
		}
		
		private void detach_Attendances(Attendance entity)
		{
			this.SendPropertyChanging();
			entity.PayrollDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _FullName;
		
		private string _Username;
		
		private string _Password;
		
		private string _SecretQuestion;
		
		private string _SecretAnswer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSecretQuestionChanging(string value);
    partial void OnSecretQuestionChanged();
    partial void OnSecretAnswerChanging(string value);
    partial void OnSecretAnswerChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretQuestion", DbType="VarChar(50)")]
		public string SecretQuestion
		{
			get
			{
				return this._SecretQuestion;
			}
			set
			{
				if ((this._SecretQuestion != value))
				{
					this.OnSecretQuestionChanging(value);
					this.SendPropertyChanging();
					this._SecretQuestion = value;
					this.SendPropertyChanged("SecretQuestion");
					this.OnSecretQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecretAnswer", DbType="VarChar(50)")]
		public string SecretAnswer
		{
			get
			{
				return this._SecretAnswer;
			}
			set
			{
				if ((this._SecretAnswer != value))
				{
					this.OnSecretAnswerChanging(value);
					this.SendPropertyChanging();
					this._SecretAnswer = value;
					this.SendPropertyChanged("SecretAnswer");
					this.OnSecretAnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
